target-version = "py312"
line-length = 100

[lint]
select = ["E", "F", "W", "I", "UP", "B", "C4"]
ignore = ["E501"]   # line length enforced by formatter not linter

[format]
quote-style = "double"
indent-style = "space"
